
## SCREEN SIZE

# Number of rows and columns.
# The value is auto-calculated if no/false/null
nlines: no
ncols: no

# Minimum number of lines and columns.
nlines_min: 1
ncols_min: 1

# If nlines/ncols are auto-calculated, they will be reduced by
# this number. You can use this e.g. to not overlap with the
# vertical scrollbar if there is one.
nlines_sub: 0
ncols_sub: 0


## BUFFERS

# The terminal normally comes with two buffers (two
# screens). Each has its own scrollback. The number of lines can
# be customized, and they will be grouped in blocks of size
# scroll_chunk.

screens:

  # 0
  # Main screen (default)
  - scrollback: 1000
    scroll_chunk: 100

  # 1
  # The alternate screen, used by most full-screen applications like
  # emacs, vi, screen, etc. has no scrollback.
  - scrollback: 0
    scroll_chunk: 100

  # You can add more screens if it suits your fancy, but right now
  # there is no way to access them.


## SCROLLING
  
scrolling:
  # If true, we use jscrollpane to display scrollbars. If
  # false, we use the standard OS-issue scrollbars.
  jscrollpane: false
  
  # true iff we want a horizontal scrollbar when appropriate
  # note: if jscrollpane is false, use css on .center (overflow-x = auto or hidden)
  scrollh: true
  
  # true iff we want a vertical scrollbar when appropriate
  # note: if jscrollpane is false, use css on .center (overflow-y = auto or hidden)
  # note: a false value is somewhat buggy with jscrollpane
  scrollv: true

